contact_links:
  - name: ğŸ“œ å®˜æ–¹æ–‡æ¡£ | GO Ldap Admin Doc
    url: http://demo.com
    about: å…³äºé¡¹ç›®çš„åŠŸèƒ½ç”¨æ³•ä»¥åŠè®¾è®¡è€ƒé‡ï¼Œéƒ½ä¼šåœ¨å®˜ç½‘è¿›è¡Œå‘ˆç°ï¼Œæäº¤é—®é¢˜ä¹‹å‰ï¼Œè¯·å…ˆé˜…è¯»å®˜æ–¹æ–‡æ¡£ï¼Œå¦‚æœè¿˜ä¸èƒ½æ»¡è¶³ï¼Œåˆ™å†æé—®é¢˜ã€‚
  - name: ğŸ‘€ Githubè®ºå› | GitHub Discussions
    url: https://github.com/ileostar/contributors
    about: å¦‚æœæ‚¨çš„é—®é¢˜ä¸æ˜¯åŠŸèƒ½æˆ–è€…é”™è¯¯ï¼Œè¯·è½¬åˆ°è®¨è®ºé¢æ¿å¹¶åœ¨æäº¤ä¹‹å‰æ£€ç´¢æ‚¨çš„é—®é¢˜æ˜¯å¦å·²ç»å­˜åœ¨ã€‚
  - name: ğŸ™Œ è´¡çŒ®æŒ‡å— | Contribution Guide
    url: https://github.com/ileostar/contribute
    about: è¯·åœ¨æè´¡çŒ®PRå‰é˜…è¯»è¯¥æŒ‡å—ï¼Œæ¬¢è¿æPR
